### ISSUE TITLE
Assignee Select: Ability to remove users when mixed

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-react-components#174]
## Story

Lots of different tasks are selected and have different assignees but I want to remove a specific assignee from all of them.

## TODO

- [x] When the values are mixed, no users should be selected.
- [ ] The user that is on the most tasks should be sorted to the top.
- [x] Ability to unassign/clear all assignees for multi/single select.
- [x] Ability to remove an assignee without selecting it with an "close" (X) icon.

### Attachments

![image](https://github.com/user-attachments/assets/f4e022f0-ce4b-4c90-a8b7-046b7d872588)
